services:
  backend:
    build: ./
    restart: always
    ports:
      - 80:80
    environment:
      - MONGODB_PASSWORD
      - MONGODB_URL
      - JWT_ALGORITHM
      - JWT_EXP_DAYS
      - JWT_SECRET
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_SERER
      - POSTGRES_PORT
      - POSTGRES_DB
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data/
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "5050:80"

volumes:
  pgdata: